name: Build and Rebuild Ploutus

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore PloutusRebuilder.fsproj -r win-x86

    - name: Publish Rebuilder (win-x86)
      run: dotnet publish PloutusRebuilder.fsproj -c Release -r win-x86 --no-restore -o publish

    - name: Run Rebuilder
      shell: cmd
      run: |
        set SAMPLE_NAME=PloutusD_d93342bd12ef44d92bf58ed2f0f88443385a0192804a5d0976352484c0d37685.exe
        
        rem Move to the publish directory
        cd publish
        
        rem Copy the malware sample to the publish directory
        copy "..\%SAMPLE_NAME%" .
        
        rem Run the rebuilder (this runs as a 32-bit process)
        PloutusRebuilder.exe
        
        rem Copy the result back to the root
        copy "%SAMPLE_NAME%_rebuilt" "..\PloutusD_rebuilt.exe"

    - name: Upload Rebuilt Binary
      uses: actions/upload-artifact@v4
      with:
        name: Ploutus-Rebuilt
        path: PloutusD_rebuilt.exe
